stages:
  download:  {cmd: clob download, outs: [data/raw]}
  preprocess:{cmd: clob preprocess, deps: [data/raw], outs: [data/processed]}
  train:
    cmd: clob train
    deps:
      - data/processed/btc_1sec.npz
    outs:
      - artifacts/best.ckpt
